### ISSUE TITLE
other command name

### ISSUE THREAD

**Issue by efor89** [Jannyboy11/InvSee-plus-plus#100]
hi i use essentialx invsee and ec for my players.
but i looking for a invsee plugin for offline player that my team can look in the inv.
i see your comment on spigotmc that you do this plugin for admins.
so my question can you change the commandname from /invsee to /invseeplus
and if /ec is a command to /ecplus?
that my players can use the essentialsx /invsee /ec cmd for normal use and my team can use /invseeplus and /ecplus?
or a config option to set the commands name to what i want or that i can remove the /invsee /ec command and only use the alias commands?
that it dont overwrites the essentialsx invsee and ec command

**Comment by Jannyboy11** [comment]
You can use bukkit's command.yml to do this.

**Comment by efor89** [comment]
command.yml is only for alias not for remove a command name from a plugin so i cant use your plugin.
i use essentialsx /invsee and your plugin overwrite the command.

**Comment by Jannyboy11** [comment]
It seems you don't understand aliases. The full commandname is 'invseeplusplus:invsee', you can create the alias 'invseeplus' for that one. 'invsee' is just an alias. If the 'invsee' alias still refers to 'invseeplusplus:invsee', you can make an entry in the commands.yml to make it refer to 'essentialsx:invsee'.
