### ISSUE TITLE
Support for Paper 1.20.1?

### ISSUE THREAD

**Issue by robotter112** [Jannyboy11/InvSee-plus-plus#101]
Hey, I think your plugin is mega, but unfortunately my server is running on Paper 1.20.1
and some of my plugins are not compatible with 1.20.2.
Would it be possible that there is also support for 1.20.1?

**Comment by Jannyboy11** [comment]
My advise would be to ditch those shitty plugins which prevent you from upgrading your server.
Alternatevily, you can use an older version of InvSee++. Version 0.24.9 should work.
