### ISSUE TITLE
Spigot 1.21 + Invsee++

### ISSUE THREAD

**Issue by ghost** [Jannyboy11/InvSee-plus-plus#110]
![image](https://github.com/Jannyboy11/InvSee-plus-plus/assets/137065095/8cb1ea15-cc69-435d-85d8-c9244d490e69)
Whatever i try, this is the awnser.

**Comment by jurohn** [comment]
16.06 20:04:06 [Server] Server thread/[ERROR] Error occurred while enabling InvSeePlusPlus v0.28.0 (Is it up to date?)
16.06 20:04:06 [Server] [INFO] java.lang.IncompatibleClassChangeError: class com.janboerman.invsee.spigot.api.SpectatorInventoryView has interface org.bukkit.inventory.InventoryView as super class
16.06 20:04:06 [Server] [INFO] at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
16.06 20:04:06 [Server] [INFO] at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
16.06 20:04:06 [Server] [INFO] at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
16.06 20:04:06 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:206) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
16.06 20:04:06 [Server] [INFO] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
16.06 20:04:06 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:117) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
16.06 20:04:06 [Server] [INFO] at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:112) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
16.06 20:04:06 [Server] [INFO] at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
16.06 20:04:06 [Server] [INFO] at com.janboerman.invsee.spigot.Impl_1_21.<init>(Setup.java:105) ~[?:?]
16.06 20:04:06 [Server] [INFO] at com.janboerman.invsee.spigot.SetupImpl.lambda$static$9(Setup.java:130) ~[?:?]
16.06 20:04:06 [Server] [INFO] at com.janboerman.invsee.spigot.Setup.setup(Setup.java:40) ~[?:?]
16.06 20:04:06 [Server] [INFO] at com.janboerman.invsee.spigot.InvseePlusPlus.onEnable(InvseePlusPlus.java:82) ~[?:?]
16.06 20:04:06 [Server] [INFO] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:267) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
16.06 20:04:06 [Server] [INFO] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
16.06 20:04:06 [Server] [INFO] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:492) ~[spigot-api-1.21-R0.1-SNAPSHOT.jar:?]
16.06 20:04:06 [Server] [INFO] at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugin(CraftServer.java:567) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
16.06 20:04:06 [Server] [INFO] at org.bukkit.craftbukkit.v1_21_R1.CraftServer.enablePlugins(CraftServer.java:481) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
16.06 20:04:06 [Server] [INFO] at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:641) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
16.06 20:04:06 [Server] [INFO] at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:426) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
16.06 20:04:06 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:269) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
16.06 20:04:06 [Server] [INFO] at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1017) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
16.06 20:04:06 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[spigot-1.21-R0.1-SNAPSHOT.jar:4217-Spigot-146439e-68603b1]
16.06 20:04:06 [Server] [INFO] at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

**Comment by Jannyboy11** [comment]
Looks like Spigot broke their api incompatibly. I will try to land a fix tomorrow.

**Comment by Jannyboy11** [comment]
There is a PR that fixes compatibility again in CraftBukkit; https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/pull-requests/1425/overview

I will have to update my plugin later because this PR only fixes binary compatibility, not source-compatibility; but at least when this lands users should be able to run the plugin fine again.

**Comment by Jannyboy11** [comment]
Managed to bump out a quick release: https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.29.0
I haven't tested it myself yet, but it should be good to go.

Note that if you use other plugins which hook into InvSee++, those might be broken currently.

**Comment by Jannyboy11** [comment]
> Managed to bump out a quick release: https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.29.0 I haven't tested it myself yet, but it should be good to go.
> 
> Note that if you use other plugins which hook into InvSee++, those might be broken currently.

I tested this release today and it works fine.
