### ISSUE TITLE
1.21 InvSeePlusPlus fails to load

### ISSUE THREAD

**Issue by csd4ni3l** [Jannyboy11/InvSee-plus-plus#111]
[18:26:12 ERROR]: Error occurred while enabling InvSeePlusPlus v0.28.0 (Is it up to date?)
java.lang.IncompatibleClassChangeError: class com.janboerman.invsee.spigot.api.SpectatorInventoryView has interface org.bukkit.inventory.InventoryView as super class

seems like another 1.21 issue, because inseeplusplus doesnt load, no other invsee plugins work either.

Version: 1.21 purpur
Operating system: Linux 6.8.4-pve

**Comment by Jannyboy11** [comment]
I also fixed this issue in Spigot itself, so upgrading Spigot will also fix it. See: https://github.com/Jannyboy11/InvSee-plus-plus/issues/110
