### ISSUE TITLE
1.21 Endersee

### ISSUE THREAD

**Issue by jurohn** [Jannyboy11/InvSee-plus-plus#113]
In 1.21 paper, with the newest InvSee++ version, when i pick stuff out of peoples echest, they still have it in there.
For me it looks completely empty but for the player it doesnt.

![image](https://github.com/Jannyboy11/InvSee-plus-plus/assets/137065095/edc4528c-6463-4516-82dc-3964b62ae209)

![image](https://github.com/Jannyboy11/InvSee-plus-plus/assets/137065095/bdf230c5-b539-41c0-8677-af26417fabd9)

Also, it doesnt looks to be compatible with BetterEnderchest, because the player has 6 rows and endersee doesnt.

**Comment by jurohn** [comment]
I found out that the saved enderchest which i see as operator, is an older snapshot of the users enderchest. It doesnt update anymore.

**Comment by jurohn** [comment]
Also when i put something in the users enderchest, that does not work.

**Comment by jurohn** [comment]
This probably is fully on my end, because Invsee+ simply doesnt register enderchests from BetterEnderchest (Which posts data in plugins/BetterEnderChest/chestData/ uuid's of the player

Is there any way you can make tis compatable? If BetterEnderChest is present, then read data out of that plugin?

**Comment by Jannyboy11** [comment]
You already posted the same issue last year: https://github.com/Jannyboy11/InvSee-plus-plus/issues/69#issue-1776439444
