### ISSUE TITLE
Duplicate method name startup error (1.16)

### ISSUE THREAD

**Issue by Cirkutry** [Jannyboy11/InvSee-plus-plus#130]
>Version

Arclight-1.16.5-1.0.25-7cf92be3
Java 11.0.11 by Oracle
Mods: Pixelmon-9.1.12 (Forge 36.2.34)

>Error

https://rentry.org/iq5eronu

>Info

Most likely similar to issues #108, #91, #85 and #83. Was wondering if there's a particular release that might work out.

**Comment by Jannyboy11** [comment]
This release may work for you: https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.25.1-Mohist-Catserver-1.16.5

I'll have to mark this issue as [duplicate/bug in other software] though, since the server software incorrectly things that one of the subroutines is defined twice.

**Comment by Cirkutry** [comment]
Worked perfectly! Much appreciated!
