### ISSUE TITLE
Publish releases on GitHub

### ISSUE THREAD

**Issue by TwinkleToes777** [Jannyboy11/InvSee-plus-plus#16]
Suggestion: publish releases on GitHub, because SpigotMC uses cloudflare which tends to put users in captchas and it is much harder to download. GitHub also supports RSS feed readers for releases, so users could receive notifications of InvSee++ updates in a very convenient way.

**Comment by Jannyboy11** [comment]
I'll have look at setting up a CI pipeline that accomplishes this when I push a tagged commit. I don't want to have to upload jars on both platforms. Maybe in the future I'll set up the SpigotMC page to download the jar from an external location, which will then be the latest release on github.

**Comment by Jannyboy11** [comment]
I have set up a GitHub action to compile the project: https://github.com/Jannyboy11/InvSee-plus-plus/blob/master/.github/workflows/compile.yml
I'll have a look at having it create releases later.

**Comment by Jannyboy11** [comment]
The compile workflow now creates releases automatically for tagged commits!

Latest release:
https://github.com/Jannyboy11/InvSee-plus-plus/releases/latest

**Comment by Jannyboy11** [comment]
By the way SpigotMC also has an RSS feed: https://www.spigotmc.org/forums/-/index.rss
