### ISSUE TITLE
Clear inventory/enderchest via command

### ISSUE THREAD

**Issue by TheMattVid** [Jannyboy11/InvSee-plus-plus#21]
Can you add a feature that would allow the clearing of inventories and ender chests? It does not seem that there are any mainstream plugins that can do this for offline players. It would be tremendously useful as a moderation tool.

**Comment by Jankoekenpan** [comment]
Added as of https://github.com/Jannyboy11/InvSee-plus-plus/commit/d56da286ad9d17be0fccec676bdcb2fa42f3e1cf

Once CI finishes, it can be downloaded from https://github.com/Jannyboy11/InvSee-plus-plus/releases/v0.12.6

**Comment by Jankoekenpan** [comment]
Actually, I think it's desirable to be able to specify the item type and max count, just like the vanilla command, so I'm re-opening this issue till that is implemented.

**Comment by TheMattVid** [comment]
Wow! Thank you!

**Comment by Jannyboy11** [comment]
Fixed as of https://github.com/Jannyboy11/InvSee-plus-plus/commit/55c9935374185200d85e791bf5d7ac74de7383e4
