### ISSUE TITLE
Unsupported on Paper 1.19.2

### ISSUE THREAD

**Issue by bobbyl140** [Jannyboy11/InvSee-plus-plus#24]
Dear Support, 
I have long used this plugin and love its features. I have been using it on Paper since about 1.16, however, it is refusing to start on Paper 1.19.2, with the message `Unsupported server software. Please run on (a fork of) CraftBukkit.` even though Paper is a fork of Spigot which is a fork of Bukkit. I saw a related error in a previous issue, but that was resolved for a different reason. Is this truly a compatibility issue, or is it just a mismanaged server check? Thank you.

**Comment by Jannyboy11** [comment]
Dear Bobby,
No, Paper should be supported. My guess is that you are not using the latest version of InvSee++. Could you [download it](https://github.com/jannyboy11/invsee-plus-plus/releases/latest) and try again please?
If you are already using InvSee++ v0.12.10, and the error still persists, I'll need to have an error from your console/logs.
Admittedly, the error message could be improved.
