### ISSUE TITLE
Inventory title uses UUID instead of player name when offline player is exempted from being spectated.

### ISSUE THREAD

**Issue by Jannyboy11** [Jannyboy11/InvSee-plus-plus#25]
According to SpigotMC user [Vatra](https://www.spigotmc.org/members/vatra.1618485/):

> One last thing, could you convert the uuid of the player back to a name? It just says the uuid when offline.

> Oh, I'm talking about when you try to view an exempted players inventory while he is offline. Online its fine.

The expected behaviour is that the chat message only contains the uuid, if the command was executed with a uuid argument, but for exempted offline players this also seems to happen when the provided argument is a username.

**Comment by Jankoekenpan** [comment]
https://github.com/Jannyboy11/InvSee-plus-plus/commit/ab7ae1d8c6440e525c91655d500b4fe1133d06c4
