### ISSUE TITLE
I cant use invsee++ because it doesnt let purpur

### ISSUE THREAD

**Issue by nojuslopro13** [Jannyboy11/InvSee-plus-plus#28]

**Comment by Jannyboy11** [comment]
What happens when you try it? InvSee++ should just work on Purpur.

**Comment by Jannyboy11** [comment]
![image](https://user-images.githubusercontent.com/5656370/207396354-04b5ebda-7799-40ee-a791-1e30eecf492d.png)
For me the latest InvSee++ works just fine on the latest Purpur. Are you using a different combination? In general, InvSee++ supports the latest minecraft version for every major release that was available at the time of InvSee++'s release (at most a few days after the Spigot release). So currently InvSee++ supports 1.12.2, 1.15.2, 1.16.5, 1.17.1, 1.18.2, 1.19.3 (releases 1.13.x and 1.14.x are unsupported)

**Comment by Jannyboy11** [comment]
Closing this issue since I was unable to reproduce this and the issue author is inactive.
