### ISSUE TITLE
The /invsee command doesn't exist? Disabled Essentials /invsee as well.

### ISSUE THREAD

**Issue by Kxsumi** [Jannyboy11/InvSee-plus-plus#29]
Title.
![image](https://user-images.githubusercontent.com/96434998/207188246-a308f099-ef61-4c79-b7ae-d1b28d914e44.png)
![image](https://user-images.githubusercontent.com/96434998/207188382-07302ba8-606d-43fc-b772-aa5deeadd859.png)

**Comment by Jannyboy11** [comment]
Are you sure you have permission to access the command (`invseeplusplus.invsee.view`)? If yes, could you show me any errors that popped up in the logs/console related to InvSee++?

**Comment by Kxsumi** [comment]
yep, i'm just dumb, essentials never disabled the command so that might be why, also I didn't have the perm for my specific role either. I feel that should be defaulted to op though.

**Comment by Jannyboy11** [comment]
> I feel that should be defaulted to op though.
It actually is provided to OPs by default: https://github.com/Jannyboy11/InvSee-plus-plus/blob/master/Spigot_Plugin/src/main/resources/plugin.yml#L55
