### ISSUE TITLE
AsyncTabCompleteEvent 

### ISSUE THREAD

**Issue by F3F5** [Jannyboy11/InvSee-plus-plus#31]
https://pastebin.com/mQZKsdF1

**Comment by Jannyboy11** [comment]
Is your server running in offline mode and allow players with nonstandard usernames?
Mojang [specifies](https://help.minecraft.net/hc/en-us/articles/4408950195341-Minecraft-Java-Edition-Username-VS-Gamertag-FAQ#:~:text=Accepted%20characters%3A,character%20accepted%20is%20_%20(underscore)
) that minecraft usernames adhere to the following format:
- they are between 3-16 characters long
- they allow only '_', '0'-'9', 'a'-'z' and 'A'-'Z'.

The offline player tabcompleter in InvSee++ assumes that all usernames adhere to that format, so if they don't, that can cause issues. I will address it by not tabcompleting invalid names.

**Comment by Jannyboy11** [comment]
https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.15.1
