### ISSUE TITLE
Console is spammed with the same message when running any invsee command and commands dont work

### ISSUE THREAD

**Issue by therealpyroland** [Jannyboy11/InvSee-plus-plus#49]
I have tried multiple plugin versions. server is paper 1.19.4.

what it says in console 
`[Server thread/ERROR]: null
773 | org.bukkit.command.CommandException: Unhandled exception executing command 'invsee' in plugin InvSeePlusPlus v0.21.4-SNAPSHOT
774 | at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
775 | at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
776 | at org.bukkit.craftbukkit.v1_19_R3.CraftServer.dispatchCommand(CraftServer.java:906) ~[paper-1.19.4.jar:git-Paper-"bcec5b1"]
777 | at org.bukkit.craftbukkit.v1_19_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.19.4.jar:git-Paper-"bcec5b1"]
778 | at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:264) ~[paper-1.19.4.jar:?]
779 | at net.minecraft.commands.Commands.performCommand(Commands.java:322) ~[?:?]
780 | at net.minecraft.commands.Commands.performCommand(Commands.java:306) ~[?:?]
781 | at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2290) ~[?:?]
782 | at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2250) ~[?:?]
783 | at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
784 | at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
785 | at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.4.jar:git-Paper-"bcec5b1"]
786 | at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
787 | at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
788 | at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1342) ~[paper-1.19.4.jar:git-Paper-"bcec5b1"]
789 | at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.4.jar:git-Paper-"bcec5b1"]
790 | at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
791 | at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1319) ~[paper-1.19.4.jar:git-Paper-"bcec5b1"]
792 | at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1312) ~[paper-1.19.4.jar:git-Paper-"bcec5b1"]
793 | at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
794 | at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1290) ~[paper-1.19.4.jar:git-Paper-"bcec5b1"]
795 | at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1178) ~[paper-1.19.4.jar:git-Paper-"bcec5b1"]
796 | at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-"bcec5b1"]
797 | at java.lang.Thread.run(Thread.java:831) ~[?:?]
798 | Caused by: java.lang.StackOverflowError
799 | at com.janboerman.invsee.spigot.perworldinventory.PerWorldInventorySeeApi.spectateInventory(PerWorldInventorySeeApi.java:351) ~[InvSee++.jar:?]
800 | at com.janboerman.invsee.spigot.perworldinventory.PerWorldInventorySeeApi.spectateInventory(PerWorldInventorySeeApi.java:351) ~[InvSee++.jar:?]
801 | at com.janboerman.invsee.spigot.perworldinventory.PerWorldInventorySeeApi.spectateInventory(PerWorldInventorySeeApi.java:351) ~[InvSee++.jar:?]`

The last lines are repeated over and over for around three thousand times before stopping. 

what it says in chat "Internal error has occurred while attempting to perform this command"

**Comment by Jannyboy11** [comment]
Fixed by https://github.com/Jannyboy11/InvSee-plus-plus/commit/8ab582a3308ffe69fcb02b4c120dfe694237600b, release available in ~30 minutes here: github.com/jannyboy11/invSee-plus-plus/releases/v0.21.5

**Comment by Jannyboy11** [comment]
Recommended to use https://github.com/jannyboy11/invSee-plus-plus/releases/v0.21.6 instead as it solves another PerWorldInventory integration related bug.
