### ISSUE TITLE
Use Electroid mojang-api to prevent rate-limits

### ISSUE THREAD

**Issue by kaxlabs** [Jannyboy11/InvSee-plus-plus#54]
Instead of the official Mojang API, I suggest using https://github.com/Electroid/mojang-api so that the main server never gets rate limited if too many people use the command. I believe if that happens, people will no longer be able to join the server for a while.

**Comment by kaxlabs** [comment]
I suppose it's a rather niche scenario due to the other checks in place. For reference though, Electroid's mojang-api is the most popular and widely tested third-party service.

**Comment by Jannyboy11** [comment]
I can still implement it as a UUIDResolveStrategy but not enable it by default.

**Comment by Jannyboy11** [comment]
Strategies implemented as of https://github.com/Jannyboy11/InvSee-plus-plus/commit/824053d4cd88200d160124b12470340dd55126e6.

Closing this in favour of https://github.com/Jannyboy11/InvSee-plus-plus/issues/57.
