### ISSUE TITLE
InvSee++ deletes/does not save PersistentDataContainers

### ISSUE THREAD

**Issue by Loapu** [Jannyboy11/InvSee-plus-plus#72]
If you use a plugin that sets custom PDCs it will be deleted upon modification via InvSee++.

See https://docs.papermc.io/paper/dev/pdc for documentation on PDCs.

Reproduction:
1. Set a custom PDC for a player
2. Modify their inventory via InvSee++ (Player may be offline or online)
3. The PDC is deleted after the new inventory is saved.

**Comment by Jannyboy11** [comment]
https://www.spigotmc.org/resources/invsee.82342/update?update=508623
https://github.com/Jannyboy11/InvSee-plus-plus/releases/v0.22.6
