### ISSUE TITLE
Cant edit players inventory

### ISSUE THREAD

**Issue by T05619** [Jannyboy11/InvSee-plus-plus#73]
The target is next to me and i'm using "/invsee" however when i do it i cant actually move any items in their inventory. I have Operator permissions but it doesn't work i have only the main plugin not the give/clear one which i think is the problem so might just be me being dumb but yeah. 
![image](https://github.com/Jannyboy11/InvSee-plus-plus/assets/121345768/d401fe5a-b9a1-4b94-a5c3-f3de1576ae46)

**Comment by T05619** [comment]
I was in spectator

**Comment by Jannyboy11** [comment]
Happens😅. Glad you found the cause of the issue yourself! 🙂
