### ISSUE TITLE
Modrinth page

### ISSUE THREAD

**Issue by Ompyl** [Jannyboy11/InvSee-plus-plus#76]
It would be great if the plugin would also be available on Modrinth.

**Comment by Jannyboy11** [comment]
What's the benefit of releasing it on Modrinth when it's already available on SpigotMC and Github Releases?

**Comment by Jannyboy11** [comment]
I made a page, but I'm not sure how active I'll maintain it: https://modrinth.com/plugin/invsee++

**Comment by Ompyl** [comment]
thysm

**Comment by Jannyboy11** [comment]
Still I'd like to know what are the benefits of releasing o  Modrinth.

**Comment by Ompyl** [comment]
It is just my personal pereference, bc of its clean ui, but you don't have to agree with me it was just an idea

**Comment by Jannyboy11** [comment]
Yes the only person who would be less happy about would be me, since I have to maintain that page now.
I also noticed that Modrinth moderates its mods and plugins using manual review much like the old devbukkit, so for them it creates more work too.
I hope they approve it soon.

**Comment by Ompyl** [comment]
ok, thx

**Comment by Jannyboy11** [comment]
InvSee++ has been approved in Modrinth! You can find it here: https://modrinth.com/plugin/invsee++

**Comment by Jannyboy11** [comment]
I wanted to update the plugin on modrinth today, but it won't let me sign in. You can download the new version (which works on 1.20.2) here: https://github.com/Jannyboy11/InvSee-plus-plus/releases/tag/v0.24.1
