### ISSUE TITLE
can we make this 1 plugin file instead of 3?

### ISSUE THREAD

**Issue by Texbio** [Jannyboy11/InvSee-plus-plus#77]
can we make this 1 plugin file instead of 3? I do not like the extra space that it takes up.

**Comment by Jannyboy11** [comment]
It doesn't take up extra space. All the code that is included in the give and clear addons would have to be included in the main plugin, so the main plugin would become larger, roughly equalling the total size of the 3 plugins together.
I like the current architecture for several reasons. Feel free to fork the project if you want it in just one plugin.
