### ISSUE TITLE
1.20.1 Broken

### ISSUE THREAD

**Issue by T05619** [Jannyboy11/InvSee-plus-plus#80]
I used to use the plugin on 1.19.2 server and it worked great but i changed the server to 1.20.1 and went back to the Spigot page and pressed the "download now" and put it in the plugins folder however when i load the game it doesnt work, i type "/invsee [name]" then it just says to use their username or UUID i dont know whats wrong.

**Comment by Jannyboy11** [comment]
Did you extract the jar files from the zip file?

**Comment by T05619** [comment]
![Screenshot 2023-08-21 111008](https://github.com/Jannyboy11/InvSee-plus-plus/assets/121345768/ef51ae82-c346-44a4-9d41-98450465bd21)
![Screenshot 2023-08-21 111045](https://github.com/Jannyboy11/InvSee-plus-plus/assets/121345768/cc79f096-cffb-4440-9618-7cb21c250f78)
The files arent in a zip folder and they are the newest version but it still shows that message when i type the command.

**Comment by Jannyboy11** [comment]
I need to see the error from your latest.log server log file when your server started in order to diagnose your issue.

**Comment by T05619** [comment]
[latest.log](https://github.com/Jannyboy11/InvSee-plus-plus/files/12397138/latest.log)
That's the log :)

**Comment by Jannyboy11** [comment]
I think your server is 1.20 and not 1.20.1. The problem should be fixed if you update your server.

**Comment by Jannyboy11** [comment]
Version 0.22.6 should work on 1.20. You can download it here from the version history tab: https://www.spigotmc.org/resources/invsee.82342/history

I will close this issue as there is no issue with InvSee++ on 1.20.1
