### ISSUE TITLE
Invsee Inventory Closed Event

### ISSUE THREAD

**Issue by creatorfromhell** [Jannyboy11/InvSee-plus-plus#81]
My suggestion is fairly straight forward. I would like to see an event called when another player's inventory has been closed after using Invsee to view/change it. This should allow the listening plugins to know a few things about the inventory such as:
- The owning player of said inventory
- The items currently in the inventory(maybe after invsee was used to take something out)
- The player that was viewing/modifying the inventory.

In order to make this event more efficient, this should only be called when an inventory is closed in edit mode. This is mostly because this indicates that nothing has changed if the player who closed the invsee inventory doesn't have edit permissions.

This will allow for plugins to fully be compatible with Invsee when they use player inventories for various things, but follow the idea that the API doesn't naturally provide access to modify offline player inventories.

**Comment by Jannyboy11** [comment]
Hi, I am not exactly sure what your use case is, but all these things that you mention are already possible with the current api.
The only thing that is not currently possible is to be notified when a SpectatorInventory is saved. But I don't think this is necessary. SpectatorInventories automatically get updated when modified by a player or by a different plugin. They are backed by the actual nms inventory of the target player. Hence watching another admin change the content's of a target player in real-time works so well in InvSee++. See: https://github.com/Jannyboy11/InvSee-plus-plus/wiki/Persistence#what-if-the-target-player-logs-in-while-being-spectated.

Here is an example of how to do the things that you required with the current api:
```java
import org.bukkit.event.Listener;
import org.bukkit.event.inventory.InventoryCloseEvent;
import org.bukkit.event.

class MyListener implements Listener {

    @EventHandler
    public void onClose(InventoryCloseEvent event) {
        if (event.getView() instanceof SpectatorInventoryView invseeView) {
            //get the player owning the inventory
            Target target = invseeView.getTarget();

            //items currently in the inventory:
            ItemStack[] contents = invseeView.getInventory().getContents();

            //checking whether the inventory was modified by this spectator:
            boolean changed = invseeView.getTrackedDifference().getDifference().isEmpty();

            //getting the spectating player
            HumanEntity spectator = invseeView.getPlayer();
        }
    }

}
```

Here are some links to some javadocs:
- SpectatorInventoryView: https://jannyboy11.github.io/InvSee-plus-plus/javadoc/com/janboerman/invsee/spigot/api/SpectatorInventoryView.html
- Target: https://jannyboy11.github.io/InvSee-plus-plus/javadoc/com/janboerman/invsee/spigot/api/target/Target.html
- Difference: https://jannyboy11.github.io/InvSee-plus-plus/javadoc/com/janboerman/invsee/spigot/api/logging/Difference.html

Note that Target is an algebraic data type (sum of products), you must check which implementation it is and then get properties of of those, e.g.:
```java
Target target = ...
if (target instanceof PlayerTarget playerTarget) {
    HumanEntity player = playerTarget.getPlayer();
    //can call player.getName() or player.getUniqueId() here.
} else if (target instanceof UniqueIdTarget uuidTarget) {
    UUID playerId = uuidTarget.getUniqueId();
} else if (target instanceof UsernameTarget usernameTarget) {
    String username = usernameTarget.getUsername();
}
```

Having said all of that, I think I can implement an event api that is called when a target player inventory is saved tomorrow. Do you think you still need it?

**Comment by Jannyboy11** [comment]
As of release 0.23.5-SNAPSHOT the following two events were implemented:
- com.janboerman.invsee.spigot.api.event.SpectatorInventoryOfflineCreatedEvent
- com.janboerman.invsee.spigot.api.event.SpectatorInventorySaveEvent
See https://github.com/Jannyboy11/InvSee-plus-plus/tree/ad248c3c0843407571d330d306c61d54ac30f19c/InvSee%2B%2B_Common/src/main/java/com/janboerman/invsee/spigot/api/event.

If these events suit your needs, can you close this issue?
If not, do you have more feedback for me?
Thanks!

**Comment by creatorfromhell** [comment]
It seems like the exact events I need. Much appreciated.
