### ISSUE TITLE
Cannot /invsee

### ISSUE THREAD

**Issue by Zhou-Shilin** [Jannyboy11/InvSee-plus-plus#90]
using deepl translate and some words may be strange 
I run `/invsee HildaFairy` and it outputs `/invsee <username|uuid>`
![238622B6-5375-4503-BB01-0FF7A88B0B0F](https://github.com/Jannyboy11/InvSee-plus-plus/assets/86581525/ee0cb562-4202-4ade-ac18-80e3972dd5c6)

ver: 0.25.1 / minecraft 1.20.1

**Comment by Jannyboy11** [comment]
Upgrade to Minecraft 1.20.2 or Minecraft 1.20.4, or downgrade InvSee++ to version 0.24.9.
See https://github.com/Jannyboy11/InvSee-plus-plus#supported-server-software for a list of supported server software.
