### ISSUE TITLE
Plug-in Version Issue

### ISSUE THREAD

**Issue by The-Friend-A** [Jannyboy11/InvSee-plus-plus#98]
I use Shockbyte as a Server Hoster and I added the plug-in, and it said it wasn't the proper version. I downloaded the lastest version. The server is 1
20.1. Do you know what is happening? Thank you.

**Comment by Jannyboy11** [comment]
If you want to stay on 1.20.1 for some silly reason, you can also downgrade InvSee++ to v0.24.9
